import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Rajdhani } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import 'animate.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

const rajdhani = Rajdhani({
  variable: "--font-radjhani",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

// const foco = Foco({
//   subsets: ["latin"], // Choose the subset you need
//   weight: ["400", "700"], // Add required font weights
//   variable: "--font-foco", // Optional: Define a CSS variable
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${rajdhani.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
